### ISSUE TITLE
Missing ending EOF in the code section

### ISSUE THREAD

**Issue by dunefro** [telepresenceio/telepresence.io#181]
Small change In both code section of page [page](https://www.getambassador.io/docs/telepresence/latest/howtos/package) there is a missing ending EOF
This is the code
```
cat > my-intercept.yaml <<EOF
prerequisites:
  - create: hello
workloads:
  - name: echo-easy
    intercepts:
      - handler: echo-easy
        headers:
          - value: "test"
            name: "x-intercept-id"
        previewURL:
          enable: true
connection:
  context: "default"
handlers:
  - name: echo-easy
    docker:
      image: thhal/echo-server:latest
  - name: hello
    script:
      run: echo hello
```
It should be 
```
cat > my-intercept.yaml <<EOF
prerequisites:
  - create: hello
workloads:
  - name: echo-easy
    intercepts:
      - handler: echo-easy
        headers:
          - value: "test"
            name: "x-intercept-id"
        previewURL:
          enable: true
connection:
  context: "default"
handlers:
  - name: echo-easy
    docker:
      image: thhal/echo-server:latest
  - name: hello
    script:
      run: echo hello
EOF
```
This is to be done at one more place in the same page
```
cat > echo-server.yaml <<EOF
---
apiVersion: v1
kind: Service
metadata:
  name: "echo-easy"
spec:
  type: ClusterIP
  selector:
    service: echo-easy
  ports:
    - name: proxied
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "echo-easy"
  labels:
    service: echo-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: echo-easy
  template:
    metadata:
      labels:
        service: echo-easy
    spec:
      containers:
        - name: echo-easy
          image: jmalloc/echo-server
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
```
Change
```
cat > echo-server.yaml <<EOF
---
apiVersion: v1
kind: Service
metadata:
  name: "echo-easy"
spec:
  type: ClusterIP
  selector:
    service: echo-easy
  ports:
    - name: proxied
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "echo-easy"
  labels:
    service: echo-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: echo-easy
  template:
    metadata:
      labels:
        service: echo-easy
    spec:
      containers:
        - name: echo-easy
          image: jmalloc/echo-server
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
EOF
```
